name: Build and Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Build the extension
        run: yarn build

      - name: Zip dist folder
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          cd dist
          zip -r ../kmitl-x-$VERSION.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: kmitl-x-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
